
-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES TABLE (Extends auth.users)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  display_name text,
  avatar_url text,
  cover_photo_url text,
  bio text,
  platform_role text, -- 'Artist', 'JobSeeker', etc.
  city text,
  state text,
  country text,
  experience int default 0,
  skills text[], -- Array of strings
  languages text[], -- Array of strings
  is_verified boolean default false,
  joined_date timestamp with time zone default timezone('utc'::text, now()),
  
  -- Artist Specific JSONB for flexible schema
  artist_details jsonb default '{}'::jsonb, 
  -- e.g. { "primaryCategory": "Painter", "rate": "5000" }
  
  -- Socials JSONB
  socials jsonb default '{}'::jsonb
  -- e.g. { "instagram": "...", "youtube": "..." }
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- 2. JOBS TABLE
create table public.jobs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  owner_id uuid references public.profiles(id),
  title text not null,
  company text not null,
  location text not null,
  type text not null,
  salary_range text,
  min_salary int,
  experience_required int,
  category text,
  description text,
  skills_required text[],
  is_featured boolean default false,
  apply_method text
);

alter table public.jobs enable row level security;

create policy "Jobs are viewable by everyone."
  on jobs for select
  using ( true );

create policy "Authenticated users can insert jobs."
  on jobs for insert
  with check ( auth.role() = 'authenticated' );

-- 3. PORTFOLIO ITEMS TABLE
create table public.portfolio_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  profile_id uuid references public.profiles(id) not null,
  type text not null,
  title text,
  caption text,
  media_url text,
  thumbnail_url text,
  youtube_url text
);

alter table public.portfolio_items enable row level security;

create policy "Portfolio items are viewable by everyone."
  on portfolio_items for select
  using ( true );

create policy "Users can manage own portfolio."
  on portfolio_items for all
  using ( auth.uid() = profile_id );

-- 4. WETUBE VIDEOS TABLE
create table public.videos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  creator_id uuid references public.profiles(id) not null,
  title text not null,
  description text,
  youtube_url text,
  thumbnail_url text,
  media_url text, -- For shorts/direct uploads
  video_type text default 'video', -- 'video' or 'short'
  category text,
  duration text,
  views int default 0,
  likes int default 0,
  status text default 'approved' -- 'pending', 'approved'
);

alter table public.videos enable row level security;

create policy "Videos are viewable by everyone."
  on videos for select
  using ( true );

create policy "Authenticated users can insert videos."
  on videos for insert
  with check ( auth.role() = 'authenticated' );

-- 5. MLM POSTS TABLE
create table public.mlm_posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  user_id uuid references public.profiles(id) not null,
  title text not null,
  description text,
  image_urls text[], -- Array of image URLs
  youtube_url text,
  pdf_url text,
  likes int default 0
);

alter table public.mlm_posts enable row level security;

create policy "MLM posts are viewable by everyone."
  on mlm_posts for select
  using ( true );

create policy "Authenticated users can insert mlm posts."
  on mlm_posts for insert
  with check ( auth.role() = 'authenticated' );

-- 6. CASTING PROJECTS TABLE
create table public.casting_projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  title text not null,
  type text not null, -- 'Film', 'Ad', etc.
  location text,
  budget text,
  agency_name text,
  description text,
  roles_count int default 1,
  role_requirements jsonb default '{}'::jsonb
);

alter table public.casting_projects enable row level security;

create policy "Casting projects are viewable by everyone."
  on casting_projects for select
  using ( true );
